title: liuz's personal blog
name: liuz's blog
email: liuzhuankyzy@gmail.com
description: >-
  阅读、书写和编码，输出是最好的学习方法。
baseurl: ""
url: "http://www.1zh.tech"
github_username: liuzhuan

markdown: kramdown
highlighter: rouge

permalink: pretty